spring:
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}

# Adds trace and span IDs to the Log4J 2
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId},%X{spanId}]"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
