server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: local
  cloud:
    gateway:
      routes:
        - id: port
          uri: lb://PORT
          predicates:
            - Path=/api/**
        - id: port-swagger
          uri: lb://PORT
          predicates:
            - Path=/swagger-ui/**,/v3/api-docs/**
        - id: zipkin
          uri: ${ZIPKIN_URL:http://localhost:9411}
          predicates:
            - Path=/zipkin/**
        - id: eureka
          uri: ${EUREKA_URL:http://localhost:8761}
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: eureka-static-resources
          uri: ${EUREKA_URL:http://localhost:8761}
          predicates:
            - Path=/eureka/**

---

spring:
  config:
    activate:
      on-profile: local
    import:
      "configserver:"
