server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  cloud:
    gateway:
      routes:
        - id: port
          uri: lb://PORT
          predicates:
            - Path=/api/**
        - id: port-swagger
          uri: lb://PORT
          predicates:
            - Path=/swagger-ui/**,/v3/api-docs/**
        - id: zipkin
          uri: ${ZIPKIN_URL:http://localhost:9411}
          predicates:
            - Path=/zipkin/**
        - id: eureka
          uri: ${EUREKA_URL:http://localhost:8761}
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: eureka-static-resources
          uri: ${EUREKA_URL:http://localhost:8761}
          predicates:
            - Path=/eureka/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka

# Adds trace and span IDs to Log4J2
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId},%X{spanId}]"
