server:
  port: 0
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: hangar
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432}/${DATABASE_NAME:space_port_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

springdoc:
  swagger-ui:
    path: /api/docs

# Adds trace and span IDs to Log4J2
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId},%X{spanId}]"

---

spring:
  config:
    activate:
      on-profile: test
  zipkin:
    enabled: false

eureka:
  client:
    enabled: false
