server:
  port: 0

spring:
  application:
    name: port
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

feign:
  clients:
    hangar:
      name: hangar
      path: /api/v1/spaceships
    cantina:
      name: cantina
      path: /api/v1/pilots

cors:
  enable:
    api-gateway:
      base-url: ${API_GATEWAY_URL:http://localhost:8080}

springdoc:
  swagger-ui:
    path: /api/docs

# Adds trace and span IDs to Log4J2
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId},%X{spanId}]"

---

spring:
  config:
    activate:
      on-profile: test
  zipkin:
    enabled: false
  # Mocks FeignClients' URLs for IT with Eureka disabled
  cloud:
    discovery:
      client:
        simple:
          instances:
            hangar[0]:
              uri: http://localhost:${wiremock.server.port:0}
            cantina[0]:
              uri: http://localhost:${wiremock.server.port:0}

eureka:
  client:
    enabled: false
