server:
  port: 0

spring:
  application:
    name: port
  profiles:
    active: local

feign:
  clients:
    hangar:
      name: hangar
      path: /api/v1/spaceships
    cantina:
      name: cantina
      path: /api/v1/pilots

cors:
  enable:
    api-gateway:
      base-url: ${API_GATEWAY_URL:http://localhost:8080}

springdoc:
  swagger-ui:
    path: /api/docs

---

spring:
  config:
    activate:
      on-profile: local
    import:
      "configserver:"

---

spring:
  config:
    activate:
      on-profile: test
  zipkin:
    enabled: false
  cloud:
    config:
      enabled: false
    # Mocks FeignClients' URLs for IT with Eureka disabled
    discovery:
      client:
        simple:
          instances:
            hangar[0]:
              uri: http://localhost:${wiremock.server.port:0}
            cantina[0]:
              uri: http://localhost:${wiremock.server.port:0}

eureka:
  client:
    enabled: false
