server:
  port: 0

spring:
  application:
    name: cantina
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5433}/${DATABASE_NAME:space_port_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

springdoc:
  swagger-ui:
    path: /api/docs

---

spring:
  config:
    activate:
      on-profile: local
    import:
      "configserver:"

---

spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      enabled: false
  zipkin:
    enabled: false

eureka:
  client:
    enabled: false
